### ISSUE TITLE
Only English data is in the 0.1.0 dump?

### ISSUE THREAD

**Issue by bdsinger** [langcog/childes-db#36]
Downloaded the 0.1.0 dump from http://childes-db.stanford.edu/releases.html, but only Eng-NA and Eng-UK tables are in the dataset. Are there plans to include the rest?

(Also, minor thing, at least with mariadb on a Mac, could not create a database with periods in the name, following the instructions in the "Local Installation" section of this repo's README.md, but that might just be something about my setup.)

**Comment by bdsinger** [comment]
Using 0.1.2 of the database from April 2018 has 20 rows in the collection table, so it looks like you already have made other languages available! Just need to update your link on the releases page (a dir listing shows available versions).

**Comment by smeylan** [comment]
Dee Dong in Mahesh Srinivasan's lab ran into a similar problem in March 2019

**Comment by smeylan** [comment]
this dump is no longer available on the website (now gives instructions to get directly from the database) so closing
