### ISSUE TITLE
No interactive visualizations when selecting "Dutch" 

### ISSUE THREAD

**Issue by christinabergmann** [langcog/childes-db#41]
There seem to be no data in the Dutch collection. 
Links where I observed this issue:
http://childes-db.stanford.edu/frequency.html
http://childes-db.stanford.edu/mlu.html
http://childes-db.stanford.edu/population.html

I did successfully generate figures for a sample of other languages (Spanish, Chinese, ...).

**Comment by smeylan** [comment]
Moved to `childes-db-shiny` issues
