### ISSUE TITLE
Put citation form replacements in gloss column

### ISSUE THREAD

**Issue by smeylan** [langcog/childes-db#8]
Citation form replacement should go in the gloss column and the idiosyncratic form should go in the following aux column. Currently this is reverse: the idiosyncratic form goes in the gloss and the replacement into the "replacement" column

**Comment by amsan7** [comment]
in this case i'm looking at the documentation: http://talkbank.org/manuals/CHAT.html#Replacements. For the token "whyncha" the replacement is "why don't you". Maybe we should provide a parameter to `get_tokens`?

**Comment by mikabr** [comment]
is the consensus that the gloss and replacement columns should remain as is, and `get_tokens()` should have substitute is the replacement based on an argument? (that's what e.g. nltk does)

**Comment by smeylan** [comment]
How about we have a `citation_form` column instead of replacement, and always populate it? Then  people can query the citation form instead of gloss directly from the database / we don't need any complex logic when retrieving data.

**Comment by smeylan** [comment]
we went with Mika's solution above; closing
